server:
  port: 9095

spring:
  datasource:
    url: jdbc:mysql://mysql-sims:3306/inventory?allowPublicKeyRetrieval=true&useSSL=false
    username: sims_user
    password: sims_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: latest
